color0 #14140d
color1 #ffb4ab
color2 #c6cd6e
color3 #c8c99c
color4 #96d698
color5 #c6cd6e
color6 #c8c99c
color7 #e5e3d8
color8 #929280
color9 #ffb4ab
color10 #c6cd6e
color11 #c8c99c
color12 #96d698
color13 #c6cd6e
color14 #c8c99c
color15 #e5e3d8

cursor                #e5e3d8
cursor_text_color     #14140d
background            #14140d
foreground            #e5e3d8
selection_foreground  #c9c7b4
selection_background  #474839
active_border_color   #c6cd6e
inactive_border_color #474839
url_color             #c6cd6e

active_tab_foreground   #303300
active_tab_background   #c6cd6e
inactive_tab_foreground #c9c7b4
inactive_tab_background #474839
cursor_trail_color      #c9c7b4
