# Animation Settings
animations {
    enabled = true
    
    # Bezier curves for different animation styles
    bezier = linear, 0, 0, 1, 1
    bezier = wind, 0.05, 0.9, 0.1, 1.05
    bezier = winIn, 0.1, 1.1, 0.1, 1.1
    bezier = winOut, 0.3, -0.3, 0, 1
    bezier = smoothOut, 0.36, 0, 0.66, -0.56
    bezier = smoothIn, 0.25, 1, 0.5, 1
    bezier = overshot, 0.33, 1, 0.68, 1.12
    bezier = bounce, 0.34, 1.56, 0.64, 1
    
    # Animation configurations
    animation = windows, 1, 2, wind, slide
    animation = windowsIn, 1, 2, winIn, slide
    animation = windowsOut, 1, 2, winOut, slide
    animation = windowsMove, 1, 2, wind, slide
    
    animation = border, 1, 1, linear
    #animation = borderangle, 1, 5, linear, loop
    
    animation = fade, 1, 1, smoothOut
    animation = fadeIn, 1, 1, smoothIn
    animation = fadeOut, 1, 1, smoothOut
    
    animation = workspaces, 1, 1, overshot, slidefade 20%
    animation = specialWorkspace, 1, 1, overshot, slidefadevert 20%
    
    # Layers
    animation = layers, 1, 1, smoothOut, slide
    animation = layersIn, 1, 1, smoothIn, slide
    animation = layersOut, 1, 1, smoothOut, slide
}
