# Environment sync
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

# Portals
exec-once = systemctl --user start xdg-desktop-portal
exec-once = systemctl --user start xdg-desktop-portal-hyprland

# Polkit agent
exec-once = hyprpolkitagent

# Notifications
exec-once = mako


exec-once = swaync

# Bar
exec-once = waybar

# Network and Bluetooth
exec-once = nm-applet --indicator
exec-once = blueman-applet

# Wallpaper
exec-once = swww init
exec-once = swww img ~/Pictures/Wallpapers/wallpaper.jpg

# Clipboard
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

exec-once = swayidle -w \
timeout 300 'swaylock -f -c 000000' \
timeout 600 'hyprctl dispatch dpms off' \
resume 'hyprctl dispatch dpms on'