[colors.primary]
background = '#14140d'
foreground = '#e5e3d8'
 
[colors.cursor]
text = '#e5e3d8'
cursor = '#c9c7b4' 
 
[colors.vi_mode_cursor]
text = '#14140d'
cursor = '#c6cd6e' 
 
[colors.search.matches]
foreground = '#474839' 
background = '#96d698' 
 
[colors.search.focused_match]
foreground = '#474839' 
background = '#c6cd6e' 
 
[colors.footer_bar]
foreground = '#474839' 
background = '#e5e3d8' 
 
[colors.hints.start]
foreground = '#474839' 
background = '#c8c99c' 
 
[colors.hints.end]
foreground = '#474839' 
background = '#c8c99c' 
 
[colors.selection]
text = '#14140d'
background = '#c6cd6e'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#c6cd6e' 
yellow = '#5e630d' 
blue = '#c6cd6e' 
magenta = '#96d698' 
cyan = '#c8c99c' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 